baseURL = 'https://precipire.github.io/'
languageCode = 'en-us'
title = 'Different Hats'
theme = 'cactus'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    css = ["css/custom.css"]
    mainSectionTitle = "Posts"
    colortheme = "classic"
    description = "Hi my name is Cameron (or is it?). I do way too many different things, wear a lot of different hats! From hacking to 3D printing to making games, I do it all! Come have a look."
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    showProjectsList = true
    
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1    
    [[menu.main]]
        name = "All posts"
        url = "/posts"
        weight = 2    

[[params.social]]
  name = "github"
  link = "https://github.com/Precipire"